name: echo_frame
description: "Your offline sanctuary for memories; Say hello to clutter-free nostalgia"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  window_size:
#    git:
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size
#  window_manager: ^0.3.8

  flutter_riverpod: ^3.3.1
  google_fonts: ^8.1.0
  day_night_themed_switcher: ^2.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/anim/
    - assets/images/icons/